language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
  - SYMFONY_VERSION=2.3.*

before_script:
  - composer self-update
  - php -dmemory_limit=1G composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source

script: phpunit --coverage-text
